#!/bin/bash
# This script fetches the land classification pixel value given WGS84 geographic coordinates. 
V=$(gdallocationinfo -wgs84 getClass/mountain_binary.tif $1 $2 | sed -n '4p')
V=${V:11:6}

if [ "$V" = "-9999" ]; then 
    V=$(gdallocationinfo -wgs84 getClass/reclassed.tif $1 $2 | sed -n '4p')
    echo $V
else
    V="MOUNTAIN"
    echo $V
fi